# /**
#  * Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  */

{{ $svc := .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "schema-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "schema-registry.commonLabels" . | indent 4 }}
{{- if $svc.labels }}
{{ toYaml $svc.labels | indent 4 }}
{{- end }}
  annotations:
{{ toYaml $svc.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: rest
  selector:
{{ include "schema-registry.selectorLabels" . | indent 4 }}
